
package gymManagement;

/**
 *
 * @author Michael
 */
public class homeReceptionist extends javax.swing.JFrame {

    /**
     * Creates new form home
     */
    public homeReceptionist() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        sidepanel = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        btnlogout = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        btnnewMember = new javax.swing.JButton();
        btnupdateDelete = new javax.swing.JButton();
        btnlist = new javax.swing.JButton();
        btnpayment = new javax.swing.JButton();
        btnclose = new javax.swing.JButton();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        sidepanel.setBackground(new java.awt.Color(43, 43, 57));
        sidepanel.setPreferredSize(new java.awt.Dimension(173, 690));

        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/gymImages/gym logo 2.png"))); // NOI18N
        jLabel1.setText("GYM PARADISE");

        btnlogout.setBackground(new java.awt.Color(64, 66, 88));
        btnlogout.setForeground(new java.awt.Color(255, 255, 255));
        btnlogout.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/gymImages/log out 2.png"))); // NOI18N
        btnlogout.setText("Log out");

        javax.swing.GroupLayout sidepanelLayout = new javax.swing.GroupLayout(sidepanel);
        sidepanel.setLayout(sidepanelLayout);
        sidepanelLayout.setHorizontalGroup(
            sidepanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(sidepanelLayout.createSequentialGroup()
                .addGroup(sidepanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(sidepanelLayout.createSequentialGroup()
                        .addGap(34, 34, 34)
                        .addComponent(jLabel1))
                    .addGroup(sidepanelLayout.createSequentialGroup()
                        .addGap(49, 49, 49)
                        .addComponent(btnlogout)))
                .addContainerGap(34, Short.MAX_VALUE))
        );
        sidepanelLayout.setVerticalGroup(
            sidepanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(sidepanelLayout.createSequentialGroup()
                .addGap(39, 39, 39)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 478, Short.MAX_VALUE)
                .addComponent(btnlogout)
                .addGap(76, 76, 76))
        );

        getContentPane().add(sidepanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 210, 690));

        jPanel2.setBackground(new java.awt.Color(87, 89, 112));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/gymImages/Admin profile.png"))); // NOI18N
        jLabel2.setText("Receptionist");
        jPanel2.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(780, 50, 120, -1));

        btnnewMember.setBackground(new java.awt.Color(64, 66, 88));
        btnnewMember.setForeground(new java.awt.Color(255, 255, 255));
        btnnewMember.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/gymImages/Add member.png"))); // NOI18N
        btnnewMember.setText("New Member");
        btnnewMember.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnnewMemberMouseClicked(evt);
            }
        });
        btnnewMember.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnnewMemberActionPerformed(evt);
            }
        });
        jPanel2.add(btnnewMember, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 160, 210, 160));

        btnupdateDelete.setBackground(new java.awt.Color(64, 66, 88));
        btnupdateDelete.setForeground(new java.awt.Color(255, 255, 255));
        btnupdateDelete.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/gymImages/icons8-update-file-64.png"))); // NOI18N
        btnupdateDelete.setText("Update Records");
        btnupdateDelete.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnupdateDeleteMouseClicked(evt);
            }
        });
        btnupdateDelete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnupdateDeleteActionPerformed(evt);
            }
        });
        jPanel2.add(btnupdateDelete, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 160, 210, 160));

        btnlist.setBackground(new java.awt.Color(64, 66, 88));
        btnlist.setForeground(new java.awt.Color(255, 255, 255));
        btnlist.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/gymImages/icons8-list-view-64.png"))); // NOI18N
        btnlist.setText("List of Members");
        btnlist.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnlistActionPerformed(evt);
            }
        });
        jPanel2.add(btnlist, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 330, 210, 180));

        btnpayment.setBackground(new java.awt.Color(64, 66, 88));
        btnpayment.setForeground(new java.awt.Color(255, 255, 255));
        btnpayment.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/gymImages/icons8-salary-male-64.png"))); // NOI18N
        btnpayment.setText("Payment ");
        btnpayment.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnpaymentActionPerformed(evt);
            }
        });
        jPanel2.add(btnpayment, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 330, 210, 180));

        btnclose.setBackground(new java.awt.Color(64, 66, 88));
        btnclose.setForeground(new java.awt.Color(255, 255, 255));
        btnclose.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/gymImages/close.png"))); // NOI18N
        btnclose.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btncloseMouseClicked(evt);
            }
        });
        jPanel2.add(btnclose, new org.netbeans.lib.awtextra.AbsoluteConstraints(860, 10, -1, -1));

        jLabel12.setFont(new java.awt.Font("Tahoma", 0, 36)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(255, 255, 255));
        jLabel12.setText("Home");
        jPanel2.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(159, 80, -1, -1));

        jLabel13.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/gymImages/home page 2.png"))); // NOI18N
        jPanel2.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 70, -1, -1));

        getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 0, 930, 690));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnnewMemberActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnnewMemberActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnnewMemberActionPerformed

    private void btnnewMemberMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnnewMemberMouseClicked
        
         new newMember().setVisible(true);
         
    }//GEN-LAST:event_btnnewMemberMouseClicked

    private void btnupdateDeleteMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnupdateDeleteMouseClicked
        // TODO add your handling code here:
        new updateDeleteReceptionist().setVisible(true);
    }//GEN-LAST:event_btnupdateDeleteMouseClicked

    private void btnupdateDeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnupdateDeleteActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnupdateDeleteActionPerformed

    private void btncloseMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btncloseMouseClicked
        
        System.exit(0);
        
    }//GEN-LAST:event_btncloseMouseClicked

    private void btnlistActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnlistActionPerformed
        
      new listMember().setVisible(true);  
        
    }//GEN-LAST:event_btnlistActionPerformed

    private void btnpaymentActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnpaymentActionPerformed
        
        new payment().setVisible(true);
    }//GEN-LAST:event_btnpaymentActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(homeReceptionist.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(homeReceptionist.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(homeReceptionist.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(homeReceptionist.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new homeReceptionist().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnclose;
    private javax.swing.JButton btnlist;
    private javax.swing.JButton btnlogout;
    private javax.swing.JButton btnnewMember;
    private javax.swing.JButton btnpayment;
    private javax.swing.JButton btnupdateDelete;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel sidepanel;
    // End of variables declaration//GEN-END:variables
}
