
package gymManagement;

import java.sql.*;
import javax.swing.JOptionPane;

/**
 *
 * @author  Michael
 */
public class updateDelete extends javax.swing.JFrame {

    Connection cn;
    PreparedStatement pst1,pst;
    ResultSet rs,rs1;
    Statement st;
    
    public updateDelete() {
        initComponents();
        
        myconnection();
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        sidepanel = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        btnlogout = new javax.swing.JButton();
        menupanel1 = new javax.swing.JPanel();
        btnnewMember = new javax.swing.JButton();
        btnupdateDelete = new javax.swing.JButton();
        btnlist = new javax.swing.JButton();
        btnpayment = new javax.swing.JButton();
        mainpanel = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        txtfname = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        txtlname = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        txtmnumber = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        gymtimecbox = new javax.swing.JComboBox<>();
        jLabel7 = new javax.swing.JLabel();
        txtemail = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        txtidnumber = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        txtamount = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        btnupdate = new javax.swing.JButton();
        jButton6 = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jLabel14 = new javax.swing.JLabel();
        txtmemberid = new javax.swing.JTextField();
        gendercbox = new javax.swing.JComboBox<>();
        btnclose = new javax.swing.JButton();
        btnsearch = new javax.swing.JButton();
        btnReset = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMaximumSize(new java.awt.Dimension(979, 679));
        setUndecorated(true);

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        sidepanel.setBackground(new java.awt.Color(43, 43, 57));
        sidepanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/gymImages/gym logo 2.png"))); // NOI18N
        jLabel3.setText("GYM PARADISE");
        sidepanel.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 20, -1, -1));

        btnlogout.setBackground(new java.awt.Color(64, 66, 88));
        btnlogout.setForeground(new java.awt.Color(255, 255, 255));
        btnlogout.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/gymImages/log out 2.png"))); // NOI18N
        btnlogout.setText("Log out");
        btnlogout.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnlogoutMouseClicked(evt);
            }
        });
        sidepanel.add(btnlogout, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 570, -1, -1));

        menupanel1.setBackground(new java.awt.Color(43, 43, 59));

        btnnewMember.setBackground(new java.awt.Color(43, 43, 57));
        btnnewMember.setForeground(new java.awt.Color(255, 255, 255));
        btnnewMember.setText("New Member");
        btnnewMember.setBorder(null);
        btnnewMember.setBorderPainted(false);
        btnnewMember.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnnewMemberMouseClicked(evt);
            }
        });
        btnnewMember.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnnewMemberActionPerformed(evt);
            }
        });

        btnupdateDelete.setBackground(new java.awt.Color(255, 123, 0));
        btnupdateDelete.setForeground(new java.awt.Color(255, 255, 255));
        btnupdateDelete.setText("Update & Delete Member");
        btnupdateDelete.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnupdateDeleteMouseClicked(evt);
            }
        });

        btnlist.setBackground(new java.awt.Color(64, 66, 88));
        btnlist.setForeground(new java.awt.Color(255, 255, 255));
        btnlist.setText("List of Members");
        btnlist.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnlistMouseClicked(evt);
            }
        });

        btnpayment.setBackground(new java.awt.Color(64, 66, 88));
        btnpayment.setForeground(new java.awt.Color(255, 255, 255));
        btnpayment.setText("Payment ");
        btnpayment.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnpaymentMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout menupanel1Layout = new javax.swing.GroupLayout(menupanel1);
        menupanel1.setLayout(menupanel1Layout);
        menupanel1Layout.setHorizontalGroup(
            menupanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(btnnewMember, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(btnupdateDelete, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(btnlist, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(btnpayment, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        menupanel1Layout.setVerticalGroup(
            menupanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(menupanel1Layout.createSequentialGroup()
                .addGap(52, 52, 52)
                .addComponent(btnnewMember, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnupdateDelete, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnlist, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnpayment, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(58, Short.MAX_VALUE))
        );

        sidepanel.add(menupanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 130, -1, -1));

        jPanel1.add(sidepanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 196, 690));

        mainpanel.setBackground(new java.awt.Color(87, 89, 112));
        mainpanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/gymImages/Admin profile.png"))); // NOI18N
        jLabel1.setText("ADMIN");
        mainpanel.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(810, 40, -1, -1));

        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("First Name");
        mainpanel.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 238, -1, -1));
        mainpanel.add(txtfname, new org.netbeans.lib.awtextra.AbsoluteConstraints(134, 235, 210, -1));

        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Last Name ");
        mainpanel.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 240, -1, -1));
        mainpanel.add(txtlname, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 240, 203, -1));

        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Mobile Number");
        mainpanel.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 314, -1, -1));
        mainpanel.add(txtmnumber, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 310, 210, -1));

        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("Gym Time");
        mainpanel.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 310, -1, -1));

        gymtimecbox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "05:00AM-11:00AM", "04:00PM-08:00PM" }));
        mainpanel.add(gymtimecbox, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 310, 203, -1));

        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("Email");
        mainpanel.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 383, -1, -1));
        mainpanel.add(txtemail, new org.netbeans.lib.awtextra.AbsoluteConstraints(134, 380, 210, -1));

        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setText("ID Number");
        mainpanel.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 380, -1, -1));
        mainpanel.add(txtidnumber, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 380, 205, -1));

        jLabel9.setForeground(new java.awt.Color(255, 255, 255));
        jLabel9.setText("Gender");
        mainpanel.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 443, -1, -1));
        mainpanel.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(54, 392, -1, -1));

        jLabel11.setForeground(new java.awt.Color(255, 255, 255));
        jLabel11.setText("Amount To Pay");
        mainpanel.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 506, -1, -1));
        mainpanel.add(txtamount, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 500, 201, -1));

        jLabel12.setFont(new java.awt.Font("Tahoma", 0, 36)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(255, 255, 255));
        jLabel12.setText("Update & Delete");
        mainpanel.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(159, 80, -1, -1));

        jLabel13.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/gymImages/icons8-update-file-64.png"))); // NOI18N
        mainpanel.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 80, -1, -1));

        btnupdate.setBackground(new java.awt.Color(43, 43, 57));
        btnupdate.setForeground(new java.awt.Color(255, 255, 255));
        btnupdate.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/gymImages/icons8-update-24.png"))); // NOI18N
        btnupdate.setText("update");
        btnupdate.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnupdateMouseClicked(evt);
            }
        });
        btnupdate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnupdateActionPerformed(evt);
            }
        });
        mainpanel.add(btnupdate, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 568, -1, -1));

        jButton6.setBackground(new java.awt.Color(43, 43, 57));
        jButton6.setForeground(new java.awt.Color(255, 255, 255));
        jButton6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/gymImages/delete.png"))); // NOI18N
        jButton6.setText("Delete");
        jButton6.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton6MouseClicked(evt);
            }
        });
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });
        mainpanel.add(jButton6, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 570, -1, -1));

        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        mainpanel.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        jLabel14.setForeground(new java.awt.Color(255, 255, 255));
        jLabel14.setText("Member ID");
        mainpanel.add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 189, -1, -1));
        mainpanel.add(txtmemberid, new org.netbeans.lib.awtextra.AbsoluteConstraints(134, 186, 65, -1));

        gendercbox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Male", "Female" }));
        mainpanel.add(gendercbox, new org.netbeans.lib.awtextra.AbsoluteConstraints(134, 443, -1, -1));

        btnclose.setBackground(new java.awt.Color(64, 66, 88));
        btnclose.setForeground(new java.awt.Color(255, 255, 255));
        btnclose.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/gymImages/close.png"))); // NOI18N
        btnclose.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btncloseMouseClicked(evt);
            }
        });
        mainpanel.add(btnclose, new org.netbeans.lib.awtextra.AbsoluteConstraints(890, 10, -1, -1));

        btnsearch.setBackground(new java.awt.Color(43, 43, 57));
        btnsearch.setForeground(new java.awt.Color(255, 255, 255));
        btnsearch.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/gymImages/search.png"))); // NOI18N
        btnsearch.setText("Search");
        btnsearch.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnsearchActionPerformed(evt);
            }
        });
        mainpanel.add(btnsearch, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 180, 90, 30));

        btnReset.setBackground(new java.awt.Color(43, 43, 57));
        btnReset.setForeground(new java.awt.Color(255, 255, 255));
        btnReset.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/gymImages/reset.png"))); // NOI18N
        btnReset.setText("Reset");
        btnReset.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnResetActionPerformed(evt);
            }
        });
        mainpanel.add(btnReset, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 570, 90, 30));

        jPanel1.add(mainpanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 0, 960, 690));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnlogoutMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnlogoutMouseClicked
        // TODO add your handling code here:
        int a =JOptionPane.showConfirmDialog(null,"Do you really want to log out","select",JOptionPane.YES_NO_CANCEL_OPTION);

        if(a==0)
        {
            setVisible(false);
            new Login().setVisible(true);

        }
    }//GEN-LAST:event_btnlogoutMouseClicked

    private void btnupdateMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnupdateMouseClicked
        // TODO add your handling code here:
        
    }//GEN-LAST:event_btnupdateMouseClicked

    private void jButton6MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton6MouseClicked
        // TODO add your handling code here:
        
    }//GEN-LAST:event_jButton6MouseClicked

    private void btncloseMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btncloseMouseClicked
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_btncloseMouseClicked

    private void btnnewMemberActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnnewMemberActionPerformed
        
       // new newMember().setVisible(true);
    }//GEN-LAST:event_btnnewMemberActionPerformed

    private void btnnewMemberMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnnewMemberMouseClicked
        
        new updateDelete().setVisible(false);
        new newMember().setVisible(true);
        
    }//GEN-LAST:event_btnnewMemberMouseClicked

    private void btnpaymentMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnpaymentMouseClicked
        
        new updateDelete().setVisible(false);
        new payment().setVisible(true);
        
    }//GEN-LAST:event_btnpaymentMouseClicked

    private void btnlistMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnlistMouseClicked
       
       new updateDelete().setVisible(false);
        new listMember().setVisible(true); 
        
    }//GEN-LAST:event_btnlistMouseClicked

    private void btnupdateDeleteMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnupdateDeleteMouseClicked
        
        new updateDelete().setVisible(true);
        
    }//GEN-LAST:event_btnupdateDeleteMouseClicked

    private void btnsearchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnsearchActionPerformed
        // TODO add your handling code here:
        
        int checkid=0;
        String id = txtmemberid.getText();
        
        try {
              cn= DriverManager.getConnection("jdbc:mysql://localhost/members","root",null);
              pst=cn.prepareStatement("select * from membersinfo where MemberID='"+id+"'");
              rs=pst.executeQuery();
              
              while(rs.next())
              {
                  checkid=1;
                  txtmemberid.setEditable(false);
                  txtfname.setText(rs.getString(2));
                  txtlname.setText(rs.getString(3));
                  txtmnumber.setText(rs.getString(4));
                  gymtimecbox.setSelectedItem(rs.getString(5));
                  gymtimecbox.setEditable(false);
                  txtemail.setText(rs.getString(6));
                  txtidnumber.setText(rs.getString(7));
                  gendercbox.setSelectedItem(rs.getString(8));
                  gendercbox.setEditable(false);
                  txtamount.setText(rs.getString(9));
                  
              
              }
              
              if(checkid==0)
              {
                  JOptionPane.showMessageDialog(null,"Member ID does not Exist");
                  
              }
        
        }
        
        catch(Exception  e)
        {
            JOptionPane.showMessageDialog(null, e);
        }
            
    }//GEN-LAST:event_btnsearchActionPerformed

    private void btnupdateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnupdateActionPerformed
       update();
        
    }//GEN-LAST:event_btnupdateActionPerformed

    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed
        // TODO add your handling code here:
        delete();
    }//GEN-LAST:event_jButton6ActionPerformed

    private void btnResetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnResetActionPerformed
        // TODO add your handling code here:
        setVisible(false);
        new updateDelete().setVisible(true);
    }//GEN-LAST:event_btnResetActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(updateDelete.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(updateDelete.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(updateDelete.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(updateDelete.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new updateDelete().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnReset;
    private javax.swing.JButton btnclose;
    private javax.swing.JButton btnlist;
    private javax.swing.JButton btnlogout;
    private javax.swing.JButton btnnewMember;
    private javax.swing.JButton btnpayment;
    private javax.swing.JButton btnsearch;
    private javax.swing.JButton btnupdate;
    private javax.swing.JButton btnupdateDelete;
    private javax.swing.JComboBox<String> gendercbox;
    private javax.swing.JComboBox<String> gymtimecbox;
    private javax.swing.JButton jButton6;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel mainpanel;
    private javax.swing.JPanel menupanel1;
    private javax.swing.JPanel sidepanel;
    private javax.swing.JTextField txtamount;
    private javax.swing.JTextField txtemail;
    private javax.swing.JTextField txtfname;
    private javax.swing.JTextField txtidnumber;
    private javax.swing.JTextField txtlname;
    private javax.swing.JTextField txtmemberid;
    private javax.swing.JTextField txtmnumber;
    // End of variables declaration//GEN-END:variables

    private void myconnection() {
    
        try{
            
            cn= DriverManager.getConnection("jdbc:mysql://localhost/members","root",null);
            pst1=cn.prepareStatement("update membersinfo set Firstname=?,Lastname=?,Mobilenumber=?,Email=?,IDnumber=?,Amount=? where MemberID=?");
            
            st= cn.createStatement();
            rs1=st.executeQuery("select * from membersinfo where MemberID='"+txtmemberid.getText()+"'");

        }
        catch(Exception e){
            //System.out.print(e);
            e.printStackTrace();
        }
    }

    private void update() {
        try
        {
         
            pst1.setString(1,txtfname.getText());
            pst1.setString(2,txtlname.getText());
            pst1.setString(3,txtmnumber.getText());
            pst1.setString(4,txtemail.getText());
            pst1.setString(5,txtidnumber.getText());
            pst1.setString(6,txtamount.getText());
            pst1.setString(7,txtmemberid.getText());
            pst1.executeUpdate();
            JOptionPane.showMessageDialog(null, "Changes updated Successfully");
            setVisible(false);
            new updateDelete().setVisible(true);
        }
        catch(Exception e)
        {
            e.printStackTrace();
        }
    }

    private void delete() {
        
        int a = JOptionPane.showConfirmDialog(null,"Do you really really want to delete Record?","select",JOptionPane.YES_NO_OPTION);
        if (a==0)
        {
            txtmemberid.getText();
            try
            {
                st.executeUpdate("delete from membersinfo where MemberID='"+txtmemberid.getText()+"'");
                JOptionPane.showMessageDialog(null, "Record Successfully Deleted");
                setVisible(false);
                new updateDelete().setVisible(true);
            
            }
            catch(Exception e)
            {
                e.printStackTrace();
            }
        }
        
    
    }
}
